config/routes.rb
Rails.application.routes.draw do
  namespace :account do
    resources :groups
    resources :posts
  end

  devise_for :users
  root 'groups#index' #這行代表把 localhost:3000/group 設成首頁
  resources :groups do
    member do
      post :join
      post :quit
    end

    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true

  has_many :posts, dependent: :destroy
  has_many :group_users
  has_many :members, through: :group_users, source: :user

  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
  	user && user == owner
  end

end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
belongs_to :user
belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :group, counter_cache: :posts_count
validates :content, presence: true

belongs_to :author, class_name: "User", foreign_key: :user_id

def editable_by?(user)
	user && user == author
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts

  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group

  def join!(group)
  	participated_groups << group
  end

  def quit!(group)
  	participated_groups.delete(group)
  end

  def is_member_of?(group)
  	participated_groups.include?(group)
  end  
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController

  before_action :authenticate_user!

  def index
  	@groups = current_user.participated_groups
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController

	before_action :authenticate_user!

	def index
		@posts = current_user.posts.order("updated_at DESC")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
  	@groups = Group.all
  end

  def new
  	@group = Group.new
  end

  def show
  	@group = Group.find(params[:id])
  	@posts = @group.posts
  end

  def edit
  	@group = current_user.groups.find(params[:id])
  end

  def create
  	@group = current_user.groups.new(group_params)

  	if @group.save
  		current_user.join!(@group)
  		redirect_to groups_path
  	else
  		render :new
  	end
  end

  def update
   	@group = current_user.groups.find(params[:id])

  	if @group.update(group_params)
  		redirect_to groups_path, notice: "修改討論版成功"
  	else
  		render :edit
  	end
  end

  def destroy
  	@group = current_user.groups.find(params[:id])
  	@group.destroy
  	redirect_to groups_path, alert: "討論版已刪除"
  end

  def join
  	@group = Group.find(params[:id])

  	if !current_user.is_member_of?(@group)
  		current_user.join!(@group)
  		flash[:notice] = "加入本討論版成功！"
  	else
  		flash[:warning] = "你已經是本討論版成員了！"
  	end

  	redirect_to group_path(@group)
  end

  def quit
  	@group = Group.find(params[:id])

  	if current_user.is_member_of?(@group)
  		current_user.quit!(@group)
  		flash[:alert] = "已退出本討論版！"
  	else
  		flash[:warning] = "你不是本討論版成員，怎麼退出 XD"
  	end

  	redirect_to group_path(@group)
  end

  private

  def group_params
  	params.require(:group).permit(:title, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group
  before_action :member_required, only: [:new, :create]

  def new
	@post = @group.posts.new
  end

  def edit
  	@post = current_user.posts.find(params[:id])
  end

  def create
  	@post = @group.posts.build(post_params)
  	@post.author = current_user

  	if @post.save
  		redirect_to group_path(@group), notice: "新增文章成功！"
  	else
  		render :new
  	end
  end

  def update
  	@post = current_user.posts.find(params[:id])

  	if @post.update(post_params)
  		redirect_to group_path(@group), notice: "文章修改成功！"
  	else
  		render :edit
  	end
  end

  def destroy
  	@post = current_user.posts.find(params[:id])

  	@post.destroy
  	redirect_to group_path(@group), alert: "文章已刪除"
  end

  private
  def find_group
  	@group = Group.find(params[:group_id])
  end

  def post_params
  	params.require(:post).permit(:content)
  end

  def member_required
  	if !current_user.is_member_of?(@group)
  		flash[:warning] = "你不是這個討論版的成員，不能發文喔！"
  		redirect_to group_path(@group)
  	end
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
  	alert_types = { notice: :success, alert: :danger }

  	close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
  	close_button = content_tag(:button, "x", close_button_options)

  	alerts = flash.map do |type, message|
  		alert_content = close_button + message

  		alert_type = alert_types[type.to_sym] || type
  		alert_class = "alert alert-#{alert_type} alert-dismissable"

  		content_tag(:div, alert_content, class: alert_class)
  	end

  	alerts.join("\n").html_safe
  end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2016 Rails101
    <br>Design by <a href="courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">新傳產獵才網</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li> <%= link_to("註冊", new_user_registration_path) %> </li>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              hi!, <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to("My Groups", account_groups_path) %></li>
              <li> <%= link_to("My Posts", account_posts_path) %></li>
              <li> <%= link_to("帳號設定", edit_user_registration_path) %> </li)
              <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
          <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>修改討論版</h1>

  <hr>
  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title %>
      <%= f.input :description %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(truncate(group.title, length: 15), group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
          	<% if group.editable_by?(current_user) %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增討論版</h1>

  <hr>
  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
  	<%= link_to("New Post", new_group_post_path(@group),class: "btn btn-warning pull-right") %>
  	<% if @group.editable_by?(current_user) %>
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
    <% if current_user.present? %>
      <% if current_user.is_member_of?(@group) %>
        <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-danger") %>
      <% else %>
      	<%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-info") %>
      	<% end %>
    <% end %>
    <% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

  <table class="table">
  	<thead>
  		<tr>
  			<th>文章</th>
  			<th colspan="2"></th>
  		</tr>
  	</thead>
  	<tbody>
  		<% @posts.each do |post| %>
  			<tr>
  				<td><%= simple_format(post.content) %></td>
  				<td>
  					<% if post.editable_by?(current_user) %>
  					<%= link_to("Edit", edit_group_post_path(post.group, post), class: "btn btn-default btn-xs")%>
  					<%= link_to("Delete", group_post_path(post.group, post), class: "btn btn-default btn-xs", method: :delete, data: { confirm: "Are you sure?"})%>
  					<% end %>
  				</td>
  			</tr>
  			<% end %>
  		</tbody>
  	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
  	<%= render "common/navbar" %>
  	<%= notice_message %>
  	<%= yield %>
  </div>

  <%= render "common/footer" %>

</body>
</html>

app/views/posts/edit.html.erb
<h1 class="text-center">修改文章</h1>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center">新增文章</h1>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>